# .github/workflows/run-daily.yml

name: Run Screener

on:
  schedule:
    - cron: '30 13 * * *'  # 15:30 CET
    - cron: '0 16 * * *'   # 18:00 CET
    - cron: '0 19 * * *'   # 21:00 CET
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Screener
        run: python main.py

      - name: Subir resultados como artifact
        uses: actions/upload-artifact@v3
        with:
          name: resultados-short-put
          path: storage/*.csv
