name: Run Short Put Screener Daily and On Demand

on:
  schedule:
    - cron: "30 13 * * *"  # 15:30 CET
    - cron: "0 16 * * *"   # 18:00 CET
    - cron: "0 19 * * *"   # 21:00 CET
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Commit y push resultados
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "shortput-bot"
          git config user.email "bot@shortput.com"
          git add storage/*.csv storage/*.txt || echo "No hay archivos nuevos"
          git diff --cached --quiet || (
            git commit -m "Update resultados diarios" &&
            git push https://x-access-token:$PAT_TOKEN@github.com/${{ github.repository }}.git HEAD:main
          )
